version: "3.8"

services:

  php:
    build:
      context: ./
      args:
        buildno: 1
    container_name: php
    hostname: php-cont
    restart: unless-stopped
    volumes:
      - ./www:/var/www
    networks:
      - default
    healthcheck:
      test: curl -s http://nginx | grep works
      interval: 30s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx-cont
    restart: unless-stopped
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www
    ports:
      - 80:80
    networks:
      - default

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
